### PR TITLE
Added plotting and interactive support for 1D fields

### PR DESCRIPTION
**Pull request by RemiLehe**
As a follow up to #135, I added plotting and GUI (i.e. `slider`) support for the 1D fields.

@ax3l , @macgiver2b : Since you seem to currently be working with 1D fields, could you give it a try (i.e. pull and install this branch + test the slider with your data), and check that everything works fine?

Thanks!

### CODE REVIEW

**Comment by RemiLehe** [comment]
@ax3l : Would you have time to look at the PR, or should I add Soeren as a reviewer instead?

**Comment by RemiLehe** [comment]
No, problem :) You can take your time: this is not urgent. I was just wondering if @ax3l and you would have any time at all to try it.

**Comment by macgiver2b** [comment]
Hi Rémi, 

I did some tests and get_fields with plot=True works fine. However, when I try to use the slider in the jupyter notebook I get the following error: 

ts.slider()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-49771a608f87> in <module>()
----> 1 ts.slider()

/Users/henrivincenti/anaconda/lib/python2.7/site-packages/openPMD_viewer-0.3.4-py2.7.egg/opmd_viewer/openpmd_timeseries/interactive.pyc in slider(self, figsize, exclude_particle_records, **kw)
    236             step=math.ceil(1.e15 * (self.tmax - self.tmin)) / 20.,
    237             description="t (fs)")
--> 238         slider.observe( change_t, names='value', type='change')
    239         set_widget_dimensions( slider, width=500 )
    240 

AttributeError: 'FloatSlider' object has no attribute 'observe'

Do you have any idea where this could come from? I can send you my data if you need. 

Best, 

Henri

**Comment by RemiLehe** [comment]
Hi Henri,

I am guessing that this is because your version of `ipywigdets` is too old. Could you try to do
```
conda update ipywidgets
```
(or `pip install --upgrade ipywidgets` if you are not using `conda`)

**Comment by macgiver2b** [comment]
Hi Rémi, 

Thanks for your reply. I tested and it works for me!

Thanks for this PR this will be really helpful. 

Best, 

Henri

**Comment by RemiLehe** [comment]
OK, I'll merge then.

**Comment by ax3l** [comment]
thank you both! :)
sorry, I was too slow :snail:

**Pull request merged**
