### PR TITLE
Allow slice emittance calculation along arbitrary coordinates

### PR DESCRIPTION
**Pull request by soerenjalas**
Often it can be useful to calculate the slice emittance for along another coordinate than z. I changed the method so that now all particle properties can be used for slicing e.g. to calculate the energy (actually uz) dependent emittance. 

There are a few API breaking changes that we would have to decide on (they can easily be reversed)

* the input argument beam_length has now the more general name slice_range
* the slice centers are returned as a FieldMetaInformation object

### CODE REVIEW

**Comment by ax3l** [comment]
@soerenjalas can you please rebase, remove already merged commits and squash together commits that change the same aspect?

**Comment by soerenjalas** [comment]
Ahhh... this is getting out of hand and I'm too much of a git noob. I will create a new branch and PR, sorry.

**Comment by RemiLehe** [comment]
OK, thanks @soerenjalas. Could actually wait until I update `upcoming-1.0` and then start your new branch from that?
Thanks!

**Comment by RemiLehe** [comment]
@soerenjalas I just updated the `upcoming-1.0` branch. You can use it now.

**Pull request closed without merging**
