### PR TITLE
add backend choice option

### PR DESCRIPTION
**Pull request by hightower8083**
sketch of the backend choice option
**For demonstration purpose, not to merge**

### CODE REVIEW

**Comment by ax3l** [comment]
Could one also implement this as a module property?

**Comment by hightower8083** [comment]
@ax3l well I'm not sure we use that much the module properties in python.. 
Can you explain in a few more words  the expected behaviour ?

**Comment by RemiLehe** [comment]
I actually like the approach used here by @hightower8083 to let each `OpenPMDTimeSeries` object have their own backend (with reasonable defaults, i.e. using `openpmd-api` whenever it is available).
This gives more freedom to the user, and allows workflow where they can use different backends within the same notebook.

I proposed some additional changes [in this PR](https://github.com/hightower8083/openPMD-viewer/pull/3).
@hightower8083 If you agree with these changes, you can merge that PR, and then we could consider merging this into the main repository.

**Comment by hightower8083** [comment]
structure looks good to me

**Pull request merged**
