### PR TITLE
Close #4: Add options for particle selection

### LINKED ISSUE #4: Add options for particle selection
The syntax should use a dictionary, as in the case of the Warp OpenPMD output.

The interactive GUI should be updated accordingly.

### PR DESCRIPTION
**Pull request by RemiLehe**
I implemented particle selection both at the API level and GUI level.

I tested the code, but it is always good that someone else also tests it on their own computer. Also, if you have any suggestion for the form of the API or the GUI, please do not hesitate.

Otherwise, you can merge the pull request. I'll try to add particle selection in the notebook tutorials soon.

### CODE REVIEW

**Comment by soerenjalas** [comment]
Nice! We still have to adapt the methods in `LpaDiagnostic` but I can do that in a different pull request. I hope I find time tomorrow to review and test the code.

**Comment by RemiLehe** [comment]
Yes, that's correct! I forgot to modify the LpaDiagnostic class ; thanks for reminding me about it. 
You can go ahead and modify it whenever you have time.

**Comment by soerenjalas** [comment]
Sorry that it took so long, but I tested the code and it works great. Thanks! You can go ahead and merge it.

**Comment by RemiLehe** [comment]
Thanks for testing this !

**Pull request merged**
