### PR TITLE
Close #99: axisLabels not Evaluated

### LINKED ISSUE #99: axisLabels not Evaluated
Plotting e.g., 2D fields right now does not add the correct labels to the axis (e.g., they are `x`, `z` as in warp).

For that to change, we just need to read the [`axisLabels` attribute](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#required-attributes-for-each-mesh-record).

### PR DESCRIPTION
**Pull request by RemiLehe**
This PR takes into account the axis labels (whereas it was previously assumed that the labels were always 'x', 'y', 'z')

@ax3l Could you check this with a file produced by PIConGPU and make sure that everything works as you expect it ?

### CODE REVIEW

**Comment by RemiLehe** [comment]
Ok, there's some problems with Python3. I'll try to fix it.

**Comment by ax3l** [comment]
thank you!

PIConGPU testing say: 3D data looks correct with all slices, 2D has still wrong axes.

**Comment by ax3l** [comment]
related to #125

**Comment by ax3l** [comment]
I uploaded 2D3V and 3D3V example files here:
https://owncloud.hzdr.de/index.php/s/ouisGZe5M0wCVzj
password (readonly): openPMD

**Comment by ax3l** [comment]
updated examples in
  https://github.com/openPMD/openPMD-standard/issues/129

**Comment by ax3l** [comment]
- [ ] since the reader works C-style, it still needs to read `dataOrder` and invert the labels (and `gridSpacing`, etc.) for records written in `F` order

**Comment by ax3l** [comment]
trailing whitespaces, how dare you ;)

**Comment by RemiLehe** [comment]
PR is ready for merging, I think ;)

**Comment by ax3l** [comment]
review looks good, wanted to try it again with a new data set but did not get to it today.

Will still merge to `dev` already since it looks good!

**Comment by RemiLehe** [comment]
Ok, thanks!
Once you test it with one of the new dataset, please let me know how it goes.

**Pull request merged**
