### PR TITLE
Cart 1D reader 

### PR DESCRIPTION
**Pull request by macgiver2b**
Hi Remi, 

I know I should have created a derived branch from dev in my fork but I did it from Master instead to avoid having to add again the changes I made. Is that ok for you or do you prefer doing it from a derived branch of dev in my fork? 

I did the test test_tutorials.py and it passes. 

best, 

Henri

### CODE REVIEW

**Comment by RemiLehe** [comment]
Hi Henri,

Using a branch that derives from master is fine.
However, the automatic tests are failing due to some minor formatting issues. (This is because we impose the [PEP8 style guidelines](https://www.python.org/dev/peps/pep-0008/) on openPMD-viewer.)
Could you run `pep8 --ignore=E201,E202,E122,E127,E128,E131 opmd_viewer` and correct the style error?

**Comment by macgiver2b** [comment]
Hi Remi, 

 I tried your command but he asks me to modify some lines that I did not even modify and I don't understand why. 

For instance, he asks me to change "if x == true" to "if x is true". He also does not want space before ":".

Just to be sure, do you want me to modify all these statements? If yes, I'll go ahead and make the changes.  

Best, 

Henri

**Comment by ax3l** [comment]
Hi Henri, I think you want to open your PR from `dev` to `dev`, too.
We only push stable releases to `master`, new features go to `dev` :) Sorry!

**Comment by ax3l** [comment]
anyway: great PR, I need that, too! :)

**Comment by RemiLehe** [comment]
Hi Henri,

Actually, you should not implement the changes that get requested when doing `pep8 --ignore=E201,E202,E122,E127,E128,E131 opmd_viewer`. These have been already implemented in the latest `dev` branch. I think that your problems come from the fact that you started your branch from `RemiLehe/openPMD-viewer/master` which is a very old version. (Sorry for not realizing this in the first place.)

I think that, since the changes you made are not too extensive, the easiest would be to restart from scratch (i.e. deleted your local copy of openPMD-viewer on your computer, restart with `git clone git@github.com:openPMD/openPMD-viewer.git`, and follow the instructions from CONTRIBUTING.md to reimplement your changes and redo the pull request).

Then the number of corrections that get requested with `pep8 --ignore=E201,E202,E122,E127,E128,E131 opmd_viewer` will be much smaller.

**Comment by macgiver2b** [comment]
Oh sorry I did not realize either I was using your branch. I will do everything from scratch following the guidelines! 

Best, 

Henri

**Pull request closed without merging**
